import { useEffect,useState } from 'react';import { useRouter } from 'next/router';import Head from 'next/head';
import Link from 'next/link';
import { requireCustomerAuth } from '../lib/page-auth';
import { requestJson, apiErrorMessage } from '../lib/api-client';

// Server-side guard: a request without a valid session cookie is redirected
// before any of this page's markup is rendered.
export async function getServerSideProps(context) {
  return requireCustomerAuth(context);
}

const date=v=>v?new Date(v).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):'—';
export default function Notifications(){const router=useRouter();const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=()=>requestJson('/api/notifications').then(r=>{if(r.status===401){router.replace('/signin');return}if(!r.ok)throw Error(apiErrorMessage(r,'Unable to load notifications'));setItems(r.data?.notifications||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false));useEffect(()=>{load()},[]);const mark=async id=>{try{const r=await requestJson('/api/notifications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(!r.ok)throw Error(apiErrorMessage(r,'Could not mark notification as read'));setItems(xs=>xs.map(n=>n.id===id?{...n,read:true}:n))}catch(e){setError(e.message)}};const unread=items.filter(n=>!n.read).length;return <><Head><title>Notifications | TopMint</title><meta name="viewport" content="width=device-width, initial-scale=1"/></Head><main style={s.page}><header style={s.head}><Link href="/dashboard" style={s.brand}>◈ topmint</Link><button style={s.back} onClick={()=>router.push('/dashboard')}>← Overview</button></header><p style={s.eyebrow}>ACCOUNT UPDATES</p><h1 style={s.title}>Notifications</h1><p style={s.sub}>{unread} unread message{unread===1?'':'s'} · Stay informed about your account.</p>{error&&<p style={s.error}>{error} <button onClick={load} style={s.retry}>Retry</button></p>}<section style={s.card}>{loading?'Loading notifications…':items.length?items.map(n=><article key={n.id} style={s.row}><span style={{...s.dot,background:n.read?'#d1d5db':'#2b8b61'}}/><div style={{flex:1,minWidth:0}}><b>{n.title}</b><p style={s.message}>{n.message}</p><small style={s.muted}>{date(n.createdAt)}</small></div>{n.read?<span style={s.read}>Read</span>:<button style={s.button} onClick={()=>mark(n.id)}>Mark read</button>}</article>):<p style={s.empty}>You&apos;re all caught up. New account updates will appear here.</p>}</section></main></>}
const s={page:{minHeight:'100vh',background:'#f5f7f6',color:'#14211d',fontFamily:'Inter,system-ui,sans-serif',padding:'24px 20px 50px'},head:{maxWidth:980,margin:'0 auto 32px',height:55,display:'flex',justifyContent:'space-between',alignItems:'center',borderBottom:'1px solid #e3ebe5'},brand:{fontSize:22,fontWeight:850,color:'#153d2c',textDecoration:'none'},back:{padding:'10px 13px',border:'1px solid #dce5df',borderRadius:10,background:'#fff',cursor:'pointer'},eyebrow:{fontSize:10,fontWeight:800,letterSpacing:1.6,color:'#38815c'},title:{fontSize:'clamp(30px,6vw,42px)',letterSpacing:-1.5,margin:'8px 0'},sub:{color:'#718078',fontSize:14,marginBottom:24},card:{maxWidth:980,margin:'0 auto',background:'#fff',border:'1px solid #e5ece7',borderRadius:18,padding:'10px 22px'},row:{display:'flex',alignItems:'flex-start',gap:12,padding:'18px 0',borderBottom:'1px solid #edf1ee'},dot:{width:8,height:8,borderRadius:9,marginTop:6,flexShrink:0},message:{fontSize:13,color:'#65756c',lineHeight:1.6,margin:'6px 0'},muted:{fontSize:10,color:'#8a9790'},button:{background:'#174f39',color:'#fff',border:0,borderRadius:9,padding:'9px 11px',fontWeight:750,cursor:'pointer',whiteSpace:'nowrap'},read:{fontSize:10,color:'#7b8981'},empty:{padding:25,textAlign:'center',color:'#78877f',fontSize:13},error:{padding:12,borderRadius:10,background:'#fff3e0',color:'#855d16',fontSize:12},retry:{marginLeft:8},};